"""
Estimate the MNL once and export everything the browser tool needs into
docs/model_data.js as a global `MODEL_DATA` object:

  - mode metadata (order, which modes carry cost / parking)
  - estimated coefficients (b_time, b_cost, b_park, ASCs) and value of time
  - per-person attribute matrices (time, cost, park, availability)
  - observed and base predicted shares

Prediction and sensitivity then run client-side in plain JavaScript.
Run from the repo root:  python -m modechoice.export_web
"""

import json
import pathlib

import numpy as np
import pandas as pd

from . import config
from .config import MODES
from .mnl import estimate, predicted_shares

ROUND = {"time": 2, "cost": 2, "park": 1}


def build_payload():
    csv = pathlib.Path(__file__).resolve().parents[1] / "data" / "synthetic_mode_choice.csv"
    df = pd.read_csv(csv)
    res = estimate(df)

    def mat(prefix, r):
        return np.round(df[[f"{prefix}_{m}" for m in MODES]].to_numpy(float), r).tolist()

    observed = (df["chosen_mode"].value_counts(normalize=True)
                .reindex(MODES).round(4).tolist())
    base_pred = predicted_shares(df, res.params).round(4).tolist()

    payload = {
        "modes": MODES,
        "labels": {  # display names
            "Drive": "Drive", "Carpool": "Carpool", "TNC": "TNC (Uber/Lyft)",
            "PublicTransit": "Public Transit", "Bike": "Bike", "Walk": "Walk",
            "ParkRide": "Park & Ride",
        },
        "hasCost": [bool(config.HAS_COST[m]) for m in MODES],
        "hasPark": [bool(config.HAS_PARK[m]) for m in MODES],
        "coef": {
            "b_time": float(res.params[0]),
            "b_cost": float(res.params[1]),
            "b_park": float(res.params[2]),
            "asc": [0.0] + [float(v) for v in res.params[3:]],  # aligned to MODES order
        },
        "vot": round(float(res.value_of_time), 1),
        "time": mat("time", ROUND["time"]),
        "cost": mat("cost", ROUND["cost"]),
        "park": mat("park", ROUND["park"]),
        "av": df[[f"av_{m}" for m in MODES]].to_numpy(int).tolist(),
        "observed": observed,
        "basePred": base_pred,
        "n": int(len(df)),
    }
    return payload


def main():
    payload = build_payload()
    out = pathlib.Path(__file__).resolve().parents[1] / "docs" / "model_data.js"
    out.parent.mkdir(exist_ok=True)
    js = "// Auto-generated by modechoice.export_web. Do not edit by hand.\n"
    js += "window.MODEL_DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    out.write_text(js)
    print(f"Wrote {out}  ({out.stat().st_size/1024:.0f} KB)")
    print("base predicted shares:",
          {m: round(s, 3) for m, s in zip(payload["modes"], payload["basePred"])})


if __name__ == "__main__":
    main()
